# Generated by Django 5.2.6 on 2025-09-21 08:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tm', models.CharField(max_length=255, verbose_name='Name (Turkmen)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Name (Russian)')),
                ('address_tm', models.TextField(verbose_name='Address (Turkmen)')),
                ('address_ru', models.TextField(verbose_name='Address (Russian)')),
                ('capacity_min', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimum Capacity')),
                ('capacity_max', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Capacity')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Base Price')),
                ('description_tm', models.TextField(verbose_name='Description (Turkmen)')),
                ('description_ru', models.TextField(verbose_name='Description (Russian)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
                'ordering': ['name_tm'],
            },
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venues/images/', verbose_name='Image')),
                ('alt_text_tm', models.CharField(blank=True, max_length=255, verbose_name='Alt Text (Turkmen)')),
                ('alt_text_ru', models.CharField(blank=True, max_length=255, verbose_name='Alt Text (Russian)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='venues.venue', verbose_name='Venue')),
            ],
            options={
                'verbose_name': 'Venue Image',
                'verbose_name_plural': 'Venue Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('standard', 'Standard'), ('gold', 'Gold'), ('vip', 'VIP')], max_length=20, verbose_name='Package Type')),
                ('name_tm', models.CharField(max_length=100, verbose_name='Display Name (Turkmen)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Display Name (Russian)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price')),
                ('details_tm', models.TextField(verbose_name='Details (Turkmen)')),
                ('details_ru', models.TextField(verbose_name='Details (Russian)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='venues.venue', verbose_name='Venue')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['venue', 'name'],
                'unique_together': {('venue', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AvailabilityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_closed', models.BooleanField(default=True, help_text='True means venue is NOT available on this date', verbose_name='Is Closed')),
                ('reason_tm', models.CharField(blank=True, max_length=255, verbose_name='Reason (Turkmen)')),
                ('reason_ru', models.CharField(blank=True, max_length=255, verbose_name='Reason (Russian)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='venues.venue', verbose_name='Venue')),
            ],
            options={
                'verbose_name': 'Availability Block',
                'verbose_name_plural': 'Availability Blocks',
                'ordering': ['date'],
                'unique_together': {('venue', 'date')},
            },
        ),
    ]
