# Generated by Django 5.2.6 on 2025-11-21 06:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Ady')),
                ('description', models.TextField(verbose_name='Düşündiriş')),
                ('address', models.CharField(max_length=500, verbose_name='Salgy')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bir gije üçin baha')),
                ('max_guests', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Iň köp myhmanlaryň sany')),
                ('bedrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ýatylýan otaglar')),
                ('bathrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hammamlar')),
                ('area', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Meýdany (m²)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Elýeterli')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jaý',
                'verbose_name_plural': 'Jaýlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ady')),
                ('description', models.TextField(blank=True, verbose_name='Düşündiriş')),
                ('icon', models.CharField(blank=True, help_text="Icon ady (meselem: 'utensils', 'snowflake')", max_length=50, verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Işjeň')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hyzmat',
                'verbose_name_plural': 'Hyzmatlar',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='package',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='venueimage',
            name='venue',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Müşderiniň ady')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Telefon belgisi')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('check_in', models.DateField(verbose_name='Giriş senesi')),
                ('check_out', models.DateField(verbose_name='Çykyş senesi')),
                ('guests_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Myhmanlaryň sany')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jemi baha')),
                ('status', models.CharField(choices=[('pending', 'Garaşylýar'), ('confirmed', 'Tassyklandy'), ('cancelled', 'Ýatyryldy'), ('completed', 'Tamamlandy')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Bellikler')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='venues.property')),
            ],
            options={
                'verbose_name': 'Bron',
                'verbose_name_plural': 'Bronlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/', verbose_name='Surat')),
                ('is_main', models.BooleanField(default=False, verbose_name='Esasy surat')),
                ('order', models.IntegerField(default=0, verbose_name='Tertip')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='venues.property')),
            ],
            options={
                'verbose_name': 'Surat',
                'verbose_name_plural': 'Suratlar',
                'ordering': ['order', '-is_main'],
            },
        ),
        migrations.CreateModel(
            name='PropertyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Goşmaça töleg (0 = mugt)', max_digits=10, verbose_name='Baha')),
                ('is_included', models.BooleanField(default=False, help_text='Esasy bahada goşulan bolsa True', verbose_name='Bahada goşulan')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_services', to='venues.property')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_services', to='venues.service')),
            ],
            options={
                'verbose_name': 'Jaýyň hyzmaty',
                'verbose_name_plural': 'Jaýlaryň hyzmatlar',
                'unique_together': {('property', 'service')},
            },
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Mukdary')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Baha')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_services', to='venues.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.service')),
            ],
            options={
                'verbose_name': 'Bronyň hyzmaty',
                'verbose_name_plural': 'Bronlaryň hyzmatlar',
            },
        ),
        migrations.DeleteModel(
            name='AvailabilityBlock',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.DeleteModel(
            name='VenueImage',
        ),
    ]
