# Generated by Django 5.2.6 on 2025-12-23 14:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tagam ady')),
                ('description', models.TextField(blank=True, verbose_name='Düşündiriş')),
                ('category', models.CharField(choices=[('appetizer', 'Başlangyç'), ('soup', 'Çorba'), ('main_course', 'Esasy tagam'), ('side_dish', 'Garnir'), ('dessert', 'Desert'), ('beverage', 'Içgi')], max_length=20, verbose_name='Kategoriýa')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Baha')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Agramy (gram)')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Wegetarian')),
                ('is_active', models.BooleanField(default=True, verbose_name='Işjeň')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tagam',
                'verbose_name_plural': 'Tagamlar',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Salat ady')),
                ('description', models.TextField(blank=True, verbose_name='Düşündiriş')),
                ('ingredients', models.TextField(verbose_name='Düzümi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Baha')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Agramy (gram)')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Wegetarian')),
                ('is_active', models.BooleanField(default=True, verbose_name='Işjeň')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salat',
                'verbose_name_plural': 'Salatlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Mukdary')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tertip')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.dish', verbose_name='Tagam')),
            ],
            options={
                'verbose_name': 'Menýudaky tagam',
                'verbose_name_plural': 'Menýudaky tagamlar',
                'ordering': ['order', 'dish__category'],
            },
        ),
        migrations.CreateModel(
            name='MenuSalad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Mukdary')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tertip')),
                ('salad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.salad', verbose_name='Salat')),
            ],
            options={
                'verbose_name': 'Menýudaky salat',
                'verbose_name_plural': 'Menýudaky salatlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WeddingMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Menýu ady')),
                ('description', models.TextField(blank=True, verbose_name='Düşündiriş')),
                ('price_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bir adama baha')),
                ('min_guests', models.PositiveIntegerField(blank=True, null=True, verbose_name='Iň az myhmanlaryň sany')),
                ('is_active', models.BooleanField(default=True, verbose_name='Işjeň')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dishes', models.ManyToManyField(related_name='wedding_menus', through='catering.MenuDish', to='catering.dish', verbose_name='Tagamlar')),
                ('salads', models.ManyToManyField(related_name='wedding_menus', through='catering.MenuSalad', to='catering.salad', verbose_name='Salatlar')),
            ],
            options={
                'verbose_name': 'Toý menýusy',
                'verbose_name_plural': 'Toý menýulary',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='menusalad',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.weddingmenu', verbose_name='Menýu'),
        ),
        migrations.AddField(
            model_name='menudish',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.weddingmenu', verbose_name='Menýu'),
        ),
        migrations.AlterUniqueTogether(
            name='menusalad',
            unique_together={('menu', 'salad')},
        ),
        migrations.AlterUniqueTogether(
            name='menudish',
            unique_together={('menu', 'dish')},
        ),
    ]
